name: Flatter (GitHub Pages)

on:
  # Rebuild once a day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  flatter-freedesktop:
    name: Flatter (freedesktop)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:24.08
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: |
            flatpaks/sh.ppy.osu/sh.ppy.osu.yaml
            flatpaks/net.badlion.BadlionClient/net.badlion.BadlionClient.yaml
          flatpak-builder-args: |
            --install-deps-from=flathub
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-pages-artifact: true
          #upload-pages-includes: |
          #  default.css
          #  index.html

  flatter-gnome:
    name: Flatter (gnome)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:46
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: |
            flatpaks/music.deadbeef.player/music.deadbeef.player.yaml
          flatpak-builder-args: |
            --install-deps-from=flathub
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-pages-artifact: true
          #upload-pages-includes: |
          #  default.css
          #  index.html

  flatter-kde:
    name: Flatter (kde)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/kde:6.7
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: |
            flatpaks/com.pixelomer.ShijimaQt/com.pixelomer.ShijimaQt.yaml
          flatpak-builder-args: |
            --install-deps-from=flathub
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-pages-artifact: true
          #upload-pages-includes: |
          #  default.css
          #  index.html

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [flatter-freedesktop, flatter-gnome, flatter-kde]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
